"""
Honest Model Evaluation Script — AI-Powered Transaction Scrutinization Engine
==============================================================================
Evaluates the XGBoost fraud model on a temporal hold-out set (last 20% by time).

IMPORTANT CAVEATS:
  - The dataset is 100% SYNTHETIC (generated by generate_dataset.py).
  - Fraud was injected using simple rules: high amount, foreign country, e-commerce bursts.
  - All metrics reported here reflect performance on *synthetic* patterns only.
  - These numbers are NOT evidence of real-world fraud detection effectiveness.
  - On a real imbalanced dataset, accuracy alone is meaningless (predicting all-legitimate
    gives ~95% accuracy; we therefore report precision, recall, PR-AUC, and confusion matrix).

Usage:
    cd backend
    python scripts/evaluate_model.py
"""

import os
import sys
import json
import joblib
import numpy as np
import pandas as pd
from datetime import datetime

# Metrics
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    average_precision_score,
    roc_auc_score,
    brier_score_loss,
    precision_recall_curve,
)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_artifacts():
    model = joblib.load(os.path.join(BASE_DIR, "fraud_model.pkl"))
    encoders = joblib.load(os.path.join(BASE_DIR, "feature_encoders.pkl"))
    return model, encoders


def engineer_features(df: pd.DataFrame, encoders: dict) -> pd.DataFrame:
    df = df.copy()
    df["timestamp"] = pd.to_datetime(df["timestamp"])
    df = df.sort_values(by=["customer_id", "timestamp"]).reset_index(drop=True)

    # Time-of-day
    df["hour_of_day"] = df["timestamp"].dt.hour

    # Velocity (1-hour rolling window)
    df_indexed = df.set_index("timestamp")
    df["velocity_1h"] = (
        df_indexed.groupby("customer_id")["amount"]
        .transform(lambda x: x.rolling("1h").count())
        .values
        - 1
    )

    # Home country / foreign flag
    home = df.groupby("customer_id")["merchant_country_code"].agg(
        lambda x: x.value_counts().index[0]
    )
    df["home_country"] = df["customer_id"].map(home)
    df["is_foreign"] = (df["merchant_country_code"] != df["home_country"]).astype(int)

    # Categorical encoding
    cat_cols = [
        "merchant_category_code",
        "pos_entry_mode",
        "currency",
        "moto_eci_indicator",
        "three_d_secure",
    ]
    for col in cat_cols:
        df[col] = df[col].astype(str).fillna("UNKNOWN")
        le = encoders[col]
        df[col + "_enc"] = df[col].apply(
            lambda v: float(le.transform([v])[0]) if v in le.classes_ else 0.0
        )

    return df


FEATURE_NAMES = [
    "amount",
    "hour_of_day",
    "velocity_1h",
    "is_foreign",
    "merchant_category_code_enc",
    "pos_entry_mode_enc",
    "currency_enc",
    "moto_eci_indicator_enc",
    "three_d_secure_enc",
]


def run_evaluation():
    print("=" * 70)
    print("  AI-POWERED TSE — HONEST MODEL EVALUATION REPORT")
    print(f"  Run at: {datetime.now().isoformat()}")
    print("=" * 70)
    print()
    print("[NOTE] CAVEAT: Dataset is 100% SYNTHETIC. Metrics reflect artificial")
    print("   fraud patterns, NOT real-world fraud detection performance.")
    print()

    # Load
    print("[1/5] Loading model and dataset...")
    model, encoders = load_artifacts()
    data_path = os.path.join(BASE_DIR, "historical_transactions.csv")
    df = pd.read_csv(data_path)
    print(f"  Dataset: {len(df):,} rows  |  Fraud: {df['is_fraud'].sum():,} ({df['is_fraud'].mean()*100:.2f}%)")
    print(f"  Model features: {model.n_features_in_}")

    # Feature engineering
    print("[2/5] Engineering features...")
    df = engineer_features(df, encoders)

    X = df[FEATURE_NAMES].values
    y = df["is_fraud"].values

    # Temporal split — last 20% by time order (not random)
    # Prevents leakage from future velocity/geo features
    cutoff = int(len(df) * 0.8)
    X_train, X_test = X[:cutoff], X[cutoff:]
    y_train, y_test = y[:cutoff], y[cutoff:]

    split_date = df.iloc[cutoff]["timestamp"]
    print(f"  Temporal split: train={cutoff:,} / test={len(y_test):,}")
    print(f"  Test set starts at: {split_date}")
    print(f"  Test fraud prevalence: {y_test.sum():,} / {len(y_test):,} ({y_test.mean()*100:.2f}%)")

    # Inference
    print("[3/5] Running inference on test set...")
    y_prob = model.predict_proba(X_test)[:, 1]
    y_pred = model.predict(X_test)  # Uses model's default 0.5 threshold

    # ── Metrics ──────────────────────────────────────────────────────────────
    print()
    print("[4/5] Computing metrics...")
    print()

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)
    tn, fp, fn, tp = cm.ravel()
    fpr = fp / (fp + tn) if (fp + tn) > 0 else float("nan")

    print("─" * 50)
    print("  CONFUSION MATRIX (XGBoost default 0.5 threshold)")
    print("─" * 50)
    print(f"  True Negatives  (legitimate, correct):  {tn:>6,}")
    print(f"  False Positives (legitimate, flagged):  {fp:>6,}  ← false alarms")
    print(f"  False Negatives (fraud, missed):        {fn:>6,}  ← missed fraud")
    print(f"  True Positives  (fraud, caught):        {tp:>6,}")
    print(f"  False Positive Rate: {fpr:.4f}  ({fpr*100:.2f}% of legit transactions blocked)")
    print()

    # Classification report
    print("─" * 50)
    print("  CLASSIFICATION REPORT")
    print("─" * 50)
    print(classification_report(y_test, y_pred, target_names=["Legitimate", "Fraud"], digits=4))

    # Key scalar metrics
    roc_auc = roc_auc_score(y_test, y_prob)
    pr_auc = average_precision_score(y_test, y_prob)
    brier = brier_score_loss(y_test, y_prob)
    accuracy = (tp + tn) / len(y_test)

    print("─" * 50)
    print("  SUMMARY METRICS")
    print("─" * 50)
    print(f"  Accuracy:       {accuracy:.4f}  ({accuracy*100:.1f}%)")
    print(f"  ROC-AUC:        {roc_auc:.4f}  (1.0 = perfect; 0.5 = random)")
    print(f"  PR-AUC:         {pr_auc:.4f}  (key metric for imbalanced data)")
    print(f"  Brier Score:    {brier:.4f}  (lower = better calibrated)")
    print()

    # Context note about ">95% accuracy" claim
    baseline_acc = 1 - y_test.mean()
    print(f"  [!] CONTEXT: Predicting ALL transactions as legitimate gives {baseline_acc*100:.1f}% accuracy.")
    print(f"     Accuracy alone is NOT a useful metric for fraud detection.")
    print(f"     Use PR-AUC ({pr_auc:.4f}) and Recall ({tp/(tp+fn):.4f}) instead.")
    print()

    # Threshold analysis (matching BRD policy)
    print("─" * 50)
    print("  THRESHOLD ANALYSIS (gap-free policy)")
    print("─" * 50)
    for decline_t in [0.70, 0.75, 0.80]:
        review_t = 0.50
        pred_d = (y_prob >= decline_t).astype(int)
        pred_r = ((y_prob >= review_t) & (y_prob < decline_t)).astype(int)
        pred_a = (y_prob < review_t).astype(int)
        n_decline = pred_d.sum()
        n_review = pred_r.sum()
        n_approve = pred_a.sum()
        fraud_in_decline = ((pred_d == 1) & (y_test == 1)).sum()
        fraud_missed = ((pred_a == 1) & (y_test == 1)).sum()
        print(f"  Decline≥{decline_t} / Review≥{review_t}:")
        print(f"    Decline: {n_decline:,} txns ({fraud_in_decline/y_test.sum()*100:.1f}% of fraud caught in Decline)")
        print(f"    Review:  {n_review:,} txns")
        print(f"    Approve: {n_approve:,} txns ({fraud_missed} fraud missed)")
        print()

    # Feature importance
    print("─" * 50)
    print("  FEATURE IMPORTANCE (XGBoost gain)")
    print("─" * 50)
    importance = model.feature_importances_
    feat_imp = sorted(zip(FEATURE_NAMES, importance), key=lambda x: x[1], reverse=True)
    for name, imp in feat_imp:
        bar = "█" * int(imp * 40)
        print(f"  {name:<40} {imp:.4f}  {bar}")
    print()

    # Save report
    report = {
        "run_at": datetime.now().isoformat(),
        "dataset": "SYNTHETIC — do not interpret as real-world performance",
        "test_set_size": int(len(y_test)),
        "test_fraud_count": int(y_test.sum()),
        "test_fraud_rate_pct": round(y_test.mean() * 100, 2),
        "temporal_split": True,
        "metrics": {
            "accuracy": round(accuracy, 4),
            "roc_auc": round(roc_auc, 4),
            "pr_auc": round(pr_auc, 4),
            "brier_score": round(brier, 4),
            "precision_fraud": round(tp / (tp + fp), 4) if (tp + fp) > 0 else 0,
            "recall_fraud": round(tp / (tp + fn), 4) if (tp + fn) > 0 else 0,
            "false_positive_rate": round(fpr, 4),
        },
        "confusion_matrix": {"tn": int(tn), "fp": int(fp), "fn": int(fn), "tp": int(tp)},
        "feature_importance": {name: round(float(imp), 4) for name, imp in feat_imp},
        "caveat": (
            "All metrics are on synthetic data. Fraud was injected via simple rules "
            "(high amount, foreign country, e-commerce). Model learns these artificial "
            "patterns. Real-world performance would require real labeled transaction data."
        ),
    }
    report_path = os.path.join(BASE_DIR, "scripts", "evaluation_report.json")
    with open(report_path, "w") as f:
        json.dump(report, f, indent=2)

    print("[5/5] Report saved to:", report_path)
    print()
    print("=" * 70)
    print("  EVALUATION COMPLETE")
    print("=" * 70)

    return report


if __name__ == "__main__":
    run_evaluation()
